### ISSUE TITLE
加载数据集

### ISSUE THREAD

**Issue by ynu-yangpeng** [zhangxin1995/PTD#2]
super_MLP.pkl引入时ModuleNotFoundError: No module named 'sklearn.neural_network.multilayer_perceptron'，是否可以将pkl中的csklearn.neural_network.multilayer_perceptron 修改为 csklearn.neural_network.MLPClassifier

**Comment by ynu-yangpeng** [comment]
我看到你的代码里用了 pkl.load(infile,encoding='latin') 问题已经解决

**Comment by zhangxin1995** [comment]
这个不清楚是底层否有变化？如果两个实现一样的话就行，要不实验结果可能有所差异
